# Generated by Django 4.2.7 on 2023-11-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
