# Generated by Django 4.2.7 on 2023-11-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_author_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
